### ISSUE TITLE
翻訳メソッドを書くときのくふう

### ISSUE THREAD

**Issue by katorie** [katorie/depot#3]
https://github.com/katorie/depot/blob/master/app/views/carts/_cart.html.erb

`t('.title')` とか書いた時に、翻訳ymlファイルが見つからないと、そのまま `title` とか表示されちゃう

**Comment by fujimura** [comment]
![screen shot 2014-04-21 at 00 59 27](https://cloud.githubusercontent.com/assets/134072/2750903/c750d97a-c8a4-11e3-97db-52b9befae352.png)

この状態になっちゃう時の事ですかね？

**Comment by katorie** [comment]
です！！
（そうか、サンプルを貼るべきでした）

**Comment by fujimura** [comment]
御存知の通り基本的にRailsで `t` は翻訳メソッドで中身は `I18n#t` なんだけど、Viewでは違います。

ここで呼ばれてるメソッドは[`ActionView::Helpers::TranslationHelper#t`](http://api.rubyonrails.org/classes/ActionView/Helpers/TranslationHelper.html#method-i-t) で、これは [`ActionView::Helpers::TranslationHelper#translate`](http://api.rubyonrails.org/classes/ActionView/Helpers/TranslationHelper.html#method-i-translate) の別名(alias)です。
で、ドキュメントを読むと、

> Delegates to I18n#translate but also performs three additional functions.
> First, it will ensure that any thrown MissingTranslation messages will be turned into inline spans that:

とあります。つまり、I18n#translateにそのまま処理を丸投げしてるんだけど、3つ追加機能がある。一つ目が今回問題になった機能で、翻訳が無かった場合自動的に"translation missing"と書いてあるspanタグに変換してしまうというもの。

これがHTMLのタグの中身として書いてあるとこういうふうに
![screen shot 2014-04-21 at 01 09 07](https://cloud.githubusercontent.com/assets/134072/2750922/3173ff70-c8a6-11e3-8a52-bfb14a126a4f.png)
赤い部分みたいに見えるんだけど、これを`<input value="ここ">`に入れると、タグがかぶって崩れてしまう。これが上のスクリーンショットで起こっていた現象です。`t('.checkout')`がタグを生成していて、それが `<button>`タグの`value`に入ってしまっていたという。

これを避けるには

``` ruby
button_to t('.checkout'), new_order_path, method: :get
```

ではなく、

``` ruby
button_to I18n.t('.checkout'), new_order_path, method: :get
```

としてあげればOKです。こうすると`ActionView::Helpers::TranslationHelper#t`ではなく`I18n#t`が呼ばれるので、もし翻訳が無くてもタグ無しの"translation missing"が出力されます。
rails consoleで試すとこの通り。

``` ruby
irb(main):011:0> helper.t "checkout"
=> "<span class=\"translation_missing\" title=\"translation missing: en.checkout\">Checkout</span>"
irb(main):012:0> I18n.t "checkout"
=> "translation missing: en.checkout"
```

**Comment by katorie** [comment]
わおー！詳しい解説までありがとうございます！！実用的だー

**Comment by katorie** [comment]
注＞　ヘルパーでも起きる
